import Foundation

extension APKBundler {
  /// Describes the structure of a Gradle project generated by ``APKBundler``.
  struct ProjectStructure {
    /// The root directory of the project.
    var root: URL
    /// The `gradlew` executable.
    var gradlew: URL
    /// The `gradle` directory.
    var gradleDirectory: URL
    /// The `gradle/libs.versions.toml` file.
    var gradleLibsVersionsFile: URL
    /// The `gradle/wrapper` directory.
    var gradleWrapperDirectory: URL
    /// The `gradle/wrapper/gradle-wrapper.jar` file.
    var gradleWrapperJar: URL
    /// The `gradle/wrapper/gradle-wrapper.properties` config file.
    var gradleWrapperProperties: URL
    /// The `build.gradle.kts` config file.
    var gradleBuildConfig: URL
    /// The `settings.gradle.kts` config file.
    var gradleSettings: URL
    /// The `gradle.properties` config file.
    var gradleProperties: URL
    /// The `local.properties` config file.
    var localProperties: URL
    /// The `src` directory.
    var src: URL
    /// The `src/main` directory.
    var srcMain: URL
    /// The `AndroidManifest.xml` file.
    var androidManifest: URL
    /// The directory containing Java source files for the app's main package.
    var javaSourceDirectory: URL
    /// The `MainActivity.java` source file.
    var mainActivitySource: URL
    /// The project's root `CMakeLists.txt` file.
    var cmakeLists: URL
    /// The directory containing the shim Swift Bundler uses to access
    /// arbitrarily-named functions from the app's native binary.
    var shimDirectory: URL
    /// The C file containing the source code for the shim.
    var shimSource: URL
    /// The shim's header file.
    var shimHeader: URL
    /// The directory containing the compiled native libraries for each
    /// supported architecture.
    var jniLibsDirectory: URL
    /// The `src/main/res` directory.
    var resourcesDirectory: URL
    /// The resource directory holding value resources (such as `strings.xml`).
    var valuesDirectory: URL
    /// The resource directory holding the night/dark mode variants of value resources.
    var nightValuesDirectory: URL
    /// The app's themes file.
    var themesFile: URL
    /// The night/dark mode variant of the app's themes file.
    var nightThemesFile: URL
    /// The resource file holding string values.
    var stringsFile: URL
    /// The resource directory holding drawable resources (such as PNG files).
    var drawableDirectory: URL
    /// The resource directory holding drawables that must be preserved as-is
    /// even in density-specific builds. See
    /// https://developer.android.com/training/multiscreen/screendensities#mipmap
    var mipmapDirectory: URL
    /// The app's main icon file.
    var icon: URL

    /// All directories in the structure. Used when creating the structure
    /// on disk.
    private var directories: [URL] {
      [
        root, javaSourceDirectory, shimDirectory, jniLibsDirectory,
        resourcesDirectory, valuesDirectory, nightValuesDirectory,
        gradleWrapperDirectory, drawableDirectory, mipmapDirectory,
      ]
    }

    /// The name of the app's main activity.
    let mainActivityName = "MainActivity"

    init(at root: URL, forAppWithIdentifier appIdentifier: String) {
      self.root = root
      gradlew = root / "gradlew"
      gradleDirectory = root / "gradle"
      gradleLibsVersionsFile = gradleDirectory / "libs.versions.toml"
      gradleWrapperDirectory = gradleDirectory / "wrapper"
      gradleWrapperProperties = gradleWrapperDirectory / "gradle-wrapper.properties"
      gradleWrapperJar = gradleWrapperDirectory / "gradle-wrapper.jar"
      gradleBuildConfig = root / "build.gradle.kts"
      gradleSettings = root / "settings.gradle.kts"
      gradleProperties = root / "gradle.properties"
      localProperties = root / "local.properties"
      src = root / "src"
      srcMain = src / "main"
      androidManifest = srcMain / "AndroidManifest.xml"

      let identifierPath = appIdentifier.lowercased()
        .replacingOccurrences(of: ".", with: "/")
      javaSourceDirectory = srcMain / "java" / identifierPath
      mainActivitySource = javaSourceDirectory / "\(mainActivityName).java"
      cmakeLists = srcMain / "CMakeLists.txt"
      shimDirectory = srcMain / "shim"
      shimSource = shimDirectory / "shim.c"
      shimHeader = shimDirectory / "shim.h"
      jniLibsDirectory = srcMain / "jniLibs"
      resourcesDirectory = srcMain / "res"
      valuesDirectory = resourcesDirectory / "values"
      nightValuesDirectory = resourcesDirectory / "values-night"
      themesFile = valuesDirectory / "themes.xml"
      nightThemesFile = nightValuesDirectory / "themes.xml"
      stringsFile = valuesDirectory / "strings.xml"
      drawableDirectory = resourcesDirectory / "drawable"
      mipmapDirectory = resourcesDirectory / "mipmap"
      icon = mipmapDirectory / "icon.png"
    }

    /// Creates all directories (including intermediate directories) required to
    /// create this project structure.
    func createDirectories() throws(Error) {
      try Error.catch(withMessage: .failedToCreateProjectStructure(root: root)) {
        for directory in directories {
          try FileManager.default.createDirectory(at: directory)
        }
      }
    }

    /// Gets the subdirectory of 'jniLibs' used for the given architecture.
    func jniLibsSubdirectory(for architecture: BuildArchitecture) -> URL {
      jniLibsDirectory / architecture.androidName
    }
  }
}
