import Foundation
import XMLCoder
import Version

extension CLIConfiguration {
  /// MSI bundler related configuration properties.
  @Configuration(overlayable: false)
  struct MSI: Codable, Hashable, Sendable {
    /// Additional entries to add to the app's WXS configuration file before
    /// invoking the WiX CLI to produce the final MSI.
    ///
    /// For example, here's how you could set your app to auto-launch using
    /// custom WiX actions.
    ///
    /// ```toml
    /// msi.wxs_extras = [
    ///   {
    ///     tag = "CustomAction",
    ///     Id = "LaunchApplication",
    ///     Execute = "immediate",
    ///     Impersonate = "no",
    ///     Return = "asyncNoWait",
    ///     Directory = "InstallFolder",
    ///     ExeCommand = "[#MainExecutable]",
    ///   },
    ///   {
    ///     tag = "InstallExecuteSequence",
    ///     children = [
    ///       {
    ///         tag = "Custom",
    ///         Action = "LaunchApplication",
    ///         After = "InstallFinalize",
    ///       }
    ///     ]
    ///   },
    /// ]
    /// ```
    var wxsExtras: [WXSValue]?

    /// WiX extensions required to build an MSI installer of the app.
    var wixExtensions: [WiXTool.ExtensionSpecifier]?

    /// A custom upgrade code to use when generating MSIs. Setting this to the same
    /// value as previous installers generated with a different tool will make MSIs
    /// generated by Swift Bundler correctly overwrite previous versions of your app
    /// generated with the other tool. The default value is generated randomly using
    /// your app identifier as a deterministic seed.
    var upgradeCode: String?
  }
}
