import Foundation

extension CLIConfiguration {
  /// Windows related configuration properties.
  @Configuration(overlayable: false)
  struct Windows: Codable, Hashable, Sendable {
    /// A partial application manifest for a cLI's main executable. This gets merged
    /// with the default manifest generated by Swift Bundler to produce the final
    /// manifest that gets embedded within the executable.
    var manifest: WindowsApplicationManifest?
  }
}
