import Foundation

/// The Swift Bundler specific configuration of a SwiftPM product. Generally
/// contains configuration properties relating to executable products, as Swift
/// Bundler doesn't care about library products at the moment. Library-specific
/// configuration generally lives in ``TargetConfiguration``.
@Configuration(overlayable: true)
struct ProductConfiguration: Codable, Sendable {
  /// Windows-specific configuration.
  var windows: Windows?

  /// Windows-specific target configuration.
  @Configuration(overlayable: false)
  struct Windows: Codable, Sendable {
    /// A partial application manifest for an executable target. This gets merged
    /// with the default manifest generated by Swift Bundler to produce the final
    /// manifest that gets embedded within the executable.
    var manifest: WindowsApplicationManifest?
  }
}
