import Foundation
import Parsing
import Version
import ErrorKit

@Configuration(overlayable: true)
struct ProjectConfiguration: Codable, Sendable {
  /// The name of the default project generated by Swift Bundler.
  static let rootProjectName = "root"

  @ExcludeFromFlat
  var source: Source?

  @ExcludeFromFlat
  var revision: String?

  /// The builder to use when building this project's products. Required when
  /// `type` is ``ProjectType/fromSource`` or ``ProjectType/hybrid``.
  @Validate({ (builder: Builder?) throws(ConfigurationFlattener.Error) in
    switch builder {
      case .named, .none:
        break
      case .inline(let inlineBuilder):
        // Deprecated format; still need to validate it though
        guard inlineBuilder.name.hasSuffix(".swift") else {
          throw RichError(cause: Error(.projectBuilderNotASwiftFile(inlineBuilder.name)))
        }
    }
  })
  var builder: Builder?

  @ExcludeFromOverlay
  var products: [String: Product]

  @Aggregate("source")
  func flattenSource(with context: ConfigurationFlattener.Context)
    throws(ConfigurationFlattener.Error) -> Source.Flat?
  {
    if (builder == nil) != (source == nil) {
      throw ConfigurationFlattener.Error(.sourceAndBuilderMustHaveSameNilness)
    }

    return try source?.flatten( 
      withRevision: revision,
      revisionField: context.codingPath.appendingKey(ProjectConfiguration.CodingKeys.revision)
    )
  }

  enum Builder: Codable, Flattenable, Sendable {
    /// The only non-deprecated way to reference builders. References a builder
    /// from ``PackageConfiguration/builders`` by name.
    case named(String)
    /// Inline builder configuration is deprecated. Kept for compatibility.
    case inline(InlineBuilder)

    init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      do {
        let inlineBuilder = try container.decode(InlineBuilder.self)
        self = .inline(inlineBuilder)
      } catch {
        let name = try container.decode(String.self)
        self = .named(name)
      }
    }

    func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
        case .named(let name):
          try container.encode(name)
        case .inline(let inlineBuilder):
          try container.encode(inlineBuilder)
      }
    }

    enum Flat {
      case named(String)
      case inline(InlineBuilder.Flat)
    }

    func flatten(
      with context: ConfigurationFlattener.Context
    ) throws(ConfigurationFlattener.Error) -> Flat {
      switch self {
        case .named(let name):
          return .named(name)
        case .inline(let inlineBuilder):
          log.warning(
            """
            Inline project builder definitions are deprecated. Define the \
            '\(inlineBuilder.name)' at the top-level and refer to it by name instead.
            """
          )
          return .inline(try inlineBuilder.flatten(with: context))
      }
    }
  }

  enum Source: Sendable {
    case git(URL)
    case local(String)

    enum Flat {
      case local(_ path: String)
      case git(URL, requirement: APIRequirement)
    }

    /// A flattened version of source for usecases where there's a sensible
    /// default git repository (e.g. the stackotter/swift-bundler repository
    /// is the default if no builder API source is explicitly provided).
    enum FlatWithDefaultRepository {
      case local(_ path: String)
      case git(URL?, requirement: APIRequirement)

      func normalized(usingDefault defaultGitURL: URL) -> Flat {
        switch self {
          case .local(let path):
            return .local(path)
          case .git(let url, let requirement):
            return .git(url ?? defaultGitURL, requirement: requirement)
        }
      }
    }

    func flatten(
      withRevision revision: String?,
      revisionField: CodingPath
    ) throws(ConfigurationFlattener.Error) -> Flat {
      switch self {
        case .git(let url):
          guard let revision else {
            let message = ConfigurationFlattener.ErrorMessage.gitSourceMissingAPIRequirement(
              url,
              field: revisionField
            )
            throw ConfigurationFlattener.Error(message)
          }
          return .git(url, requirement: .revision(revision))
        case .local(let path):
          return .local(path)
      }
    }
  }

  enum APIRequirement {
    case revision(String)
  }

  @Configuration(overlayable: true)
  struct Product: Codable, Sendable {
    /// The product's type.
    var type: ProductType

    /// The directory to find the product within, relative to the project's
    /// build directory.
    var outputDirectory: String?

    /// The filename of the product's artifact. If not provided it's inferred
    /// from the product name and product type using platform-specific rules.
    ///
    /// Also used as the destination filename when copying the product's
    /// artifact into the products directory or embedding it in an app bundle.
    @Validate({ (filename: String?) throws(ConfigurationFlattener.Error) in
      guard let filename else { return }

      if filename.contains("/") || filename.contains("\\") {
        throw ConfigurationFlattener.Error(.filenameContainsPathSeparator(filename))
      }
    })
    var filename: String?

    /// The location to find the product's prebuilt artifact at when not
    /// performing a from-source build of the product.
    ///
    /// Available in ``ProjectType/prebuilt`` or ``ProjectType/hybrid`` projects.
    var prebuilt: PrebuiltLocation?

    /// The location to find a product's prebuilt artifact at.
    enum PrebuiltLocation: Codable, TriviallyFlattenable {
      /// The prebuilt can be found at a remote URL.
      case url(URL)
      /// The prebuilt can be found at a path relative to the project's source
      /// directory.
      case path(String)

      init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(String.self)
        let parser = OneOf {
          Parse {
            "url("
            PrefixUpTo(")")
            ")"
          }
          .map { (url: Substring) -> Result<Self, ProjectConfiguration.Error> in
            guard let url = URL(string: String(url)) else {
              return .failure(ProjectConfiguration.Error(.invalidURL(String(url))))
            }
            return .success(Self.url(url))
          }

          Parse {
            "path("
            PrefixUpTo(")")
            ")"
          }.map { path in
            Result<_, ProjectConfiguration.Error>.success(Self.path(String(path)))
          }
        }
        self = try parser.parse(value).get()
      }

      func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        let value: String
        switch self {
          case .url(let url):
            value = "url(\(url.absoluteString))"
          case .path(let path):
            value = "path(\(path))"
        }
        try container.encode(value)
      }
    }

    /// A type of product.
    enum ProductType: String, Codable, TriviallyFlattenable {
      /// A dynamic library product.
      case dynamicLibrary
      /// A static library product.
      case staticLibrary
      /// An executable product.
      case executable
    }
  }
}

extension ProjectConfiguration.Source: Codable {
  init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    let value = try container.decode(String.self)
    let parser = OneOf {
      Parse {
        "git("
        PrefixUpTo(")")
        ")"
      }
      .map { (url: Substring) -> Result<Self, ProjectConfiguration.Error> in
        guard let url = URL(string: String(url)) else {
          return .failure(ProjectConfiguration.Error(.invalidGitURL(String(url))))
        }
        return .success(Self.git(url))
      }

      Parse {
        "local("
        PrefixUpTo(")")
        ")"
      }.map { path in
        Result<_, ProjectConfiguration.Error>.success(Self.local(String(path)))
      }
    }
    self = try parser.parse(value).get()
  }

  func encode(to encoder: any Encoder) throws {
    let value: String
    switch self {
      case .git(let url):
        value = "git(\(url.absoluteString))"
      case .local(let path):
        value = "local(\(path))"
    }
    var container = encoder.singleValueContainer()
    try container.encode(value)
  }
}

extension ProjectConfiguration.APIRequirement: Codable {
  init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    let value = try container.decode(String.self)
    let parser = OneOf {
      Parse {
        "revision("
        PrefixUpTo(")")
        ")"
      }.map { revision in
        Self.revision(String(revision))
      }
    }
    self = try parser.parse(value)
  }

  func encode(to encoder: any Encoder) throws {
    let value: String
    switch self {
      case .revision(let revision):
        value = "revision(\(revision))"
    }
    var container = encoder.singleValueContainer()
    try container.encode(value)
  }
}

extension ProjectConfiguration.Source? {
  func flatten(
    withRequirement requirement: ProjectConfiguration.APIRequirement?,
    requirementField: CodingPath
  ) throws(ConfigurationFlattener.Error)
    -> ProjectConfiguration.Source.FlatWithDefaultRepository
  {
    switch self {
      case .local(let path):
        guard requirement == nil else {
          throw ConfigurationFlattener.Error(.localSourceMustNotSpecifyRevision(path))
        }
        return .local(path)
      case .git(let url):
        guard let apiRequirement = requirement else {
          throw ConfigurationFlattener.Error(
            .gitSourceMissingAPIRequirement(url, field: requirementField)
          )
        }
        return .git(url, requirement: apiRequirement)
      case nil:
        guard let apiRequirement = requirement else {
          throw ConfigurationFlattener.Error(.defaultSourceMissingAPIRequirement)
        }
        return .git(nil, requirement: apiRequirement)
    }
  }
}

extension ProjectConfiguration.Product.Flat {
  private func baseArtifactPath(whenNamed name: String, platform: Platform) -> String {
    let baseName: String
    if let filename {
      let parts = filename.split(separator: ".", omittingEmptySubsequences: false)
      if parts.count == 1 {
        baseName = filename
      } else {
        baseName = parts[..<(parts.count - 1)].joined(separator: ".")
      }
    } else {
      switch type {
        case .dynamicLibrary, .staticLibrary:
          switch platform.partitioned {
            case .linux, .apple, .android:
              baseName = "lib\(name)"
            case .windows:
              baseName = name
          }
        case .executable:
          baseName = name
      }
    }

    if let outputDirectory = outputDirectory {
      return "\(outputDirectory)/\(baseName)"
    } else {
      return baseName
    }
  }

  func artifactPath(whenNamed name: String, platform: Platform) -> String {
    if let filename {
      if let outputDirectory {
        return "\(outputDirectory)/\(filename)"
      } else {
        return filename
      }
    }

    // We include the `.` in the extension so that we can use "" to signify
    // no extension without any special case logic.
    let fileExtension: String
    switch type {
      case .dynamicLibrary:
        switch platform.partitioned {
          case .linux, .android:
            fileExtension = ".so"
          case .windows:
            fileExtension = ".dll"
          case .apple:
            fileExtension = ".dylib"
        }
      case .staticLibrary:
        // TODO: Support static libraries on Windows
        fileExtension = ".a"
      case .executable:
        switch platform.partitioned {
          case .windows:
            fileExtension = ".exe"
          case .linux, .android, .apple:
            fileExtension = ""
        }
    }

    let basePath = baseArtifactPath(whenNamed: name, platform: platform)
    return "\(basePath)\(fileExtension)"
  }

  func auxiliaryArtifactPaths(whenNamed name: String, platform: Platform) -> [String] {
    let fileExtensions: [String]
    switch platform.partitioned {
      case .windows:
        if type == .dynamicLibrary {
          fileExtensions = ["lib", "pdb"]
        } else {
          return []
        }
      case .linux, .android, .apple:
        return []
    }

    let basePath = baseArtifactPath(whenNamed: name, platform: platform)
    return fileExtensions.map { "\(basePath).\($0)" }
  }
}
