import Foundation

/// Windows related configuration properties.
@Configuration(overlayable: false)
struct WindowsConfiguration: Codable, Sendable {
  /// A partial application manifest for an app's main executable. This gets merged
  /// with the default manifest generated by Swift Bundler to produce the final
  /// manifest that gets embedded within the executable.
  var manifest: WindowsApplicationManifest?
}
